---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: gateway-system
  name: gateway-node-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gateway-node-controller
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  verbs:
  - get
  - list
  - watch
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: gateway-system
  name: gateway-node-controller
subjects:
- kind: ServiceAccount
  namespace: gateway-system
  name: gateway-node-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gateway-node-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gateway-system
  name: gateway-node-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-node-controller
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway-node-controller
    spec:
      serviceAccountName: gateway-node-controller
      containers:
      - name: gateway-controller
        image: docker.io/githubtommie/gateway-node-controller:v0.2.0
        imagePullPolicy: Always
